#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App11.Resource", IsApplication=true)]

namespace App11
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_accessibility_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int img1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int img5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int img6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int img7 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int about_app = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int button1_click = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int datePicker1 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int file_settings = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int frameLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int gridview = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int help = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int new_game1 = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int textItem = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int textView1_Date = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listViewTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int popMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
