#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App11.Resource", IsApplication=true)]

namespace App11
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_accessibility_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int img1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int img5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int img6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int img7 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int ClickToDeleteButton = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int GOtoAct2 = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int My_List_V = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int RETURNAct1 = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int about_app = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int button1 = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int button1_click = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int datePicker1 = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int file_settings = 2131165199;
			
			// aapt resource value: 0x7f070006
			public const int frameLayout1 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int gallery1 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int gridview = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int help = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int new_game1 = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int textItem = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int textView1_Date = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityTransitionLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityTransittedTo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout3 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout4 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layout5 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int listViewTemplate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int popMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int yanni = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
